spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/customer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: none
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    database: mysql
  cache:
    type: redis
    cache-names: customer
    redis:
      time-to-live: 60000
  redis:
    host: localhost
    port: 6379


server:
  port: 8081
  servlet:
    context-path: /customer-service

